apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-db-persistence-volume-claim
  namespace: account
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
