apiVersion: v1
kind: Service
metadata:
  name: ledger-api
  namespace: ledger
  labels:
    app: ledger-api
    service: ledger-api
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 80
  selector:
    app: ledger-api
    version: v1
