apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-db
  namespace: ledger
spec:
  selector:
    matchLabels:
      app: ledger-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ledger-db
    spec:
      serviceAccountName: ledger-db
      containers:
        - name: ledger-db
          image: postgres:14.8
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: ledger-persistence-volume
      volumes:
        - name: ledger-persistence-volume
          persistentVolumeClaim:
            claimName: ledger-db-persistence-volume-claim
