apiVersion: v1
kind: PersistentVolume
metadata:
  name: ledger-persistence-volume
  namespace: ledger
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minikube/directory/structure/ledger"
    type: DirectoryOrCreate
