apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ledger-db-persistence-volume-claim
  namespace: ledger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
