apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: auth
  labels:
    app: auth-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
      version: v1
  template:
    metadata:
      labels:
        app: auth-api
        version: v1
    spec:
      serviceAccountName: auth-api
      containers:
        - name: auth-api
          image: lucasgsousa/apps-banking-auth:v1
          env:
            - name: DATABASE_HOST
              value: auth-db.auth
            - name: DATABASE_PASSWORD
              value: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          securityContext:
            runAsUser: 1000
