apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-persistence-volume-claim
  namespace: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
